In [89]:
import numpy as np

In [90]:
simple_list=[3,6,9]
np.array(simple_list)

array([3, 6, 9])

In [91]:
arr=np.array([3,6,9])

In [92]:
arr

array([3, 6, 9])

In [93]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [95]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [96]:
np.arange(1,5,3)

array([1, 4])

In [97]:
np.arange(1,32,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [98]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.zeros(9,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [102]:
np.ones(7,int)

array([1, 1, 1, 1, 1, 1, 1])

In [103]:
np.ones(2,3)

TypeError: Cannot interpret '3' as a data type

In [106]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [107]:
np.ones((7,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [108]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [109]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [110]:
np.linspace(0,25,12)

array([ 0.        ,  2.27272727,  4.54545455,  6.81818182,  9.09090909,
       11.36363636, 13.63636364, 15.90909091, 18.18181818, 20.45454545,
       22.72727273, 25.        ])

In [111]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [112]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [113]:
np.random.rand(3,4)

array([[0.18004739, 0.71231955, 0.79164521, 0.25124757],
       [0.57999573, 0.73258458, 0.79279234, 0.84643478],
       [0.72853941, 0.84067681, 0.2034453 , 0.08684392]])

In [114]:
arr=np.random.randn(3,4)
arr

array([[-0.72885228, -0.27813204, -1.45144944,  1.40042382],
       [ 0.83736605, -0.32650565, -1.4187041 , -1.40561807],
       [ 1.58059803,  1.69043859, -0.80960288, -0.53203645]])

In [115]:
np.random.randn(3,4)

array([[-0.97726043,  0.40274875, -1.16950914, -0.97165136],
       [-0.78320729,  1.86413097,  1.42145274,  1.85324404],
       [-0.50782829,  1.54513278, -2.36582353, -0.63259643]])

In [116]:
np.random.randint(2,100)

31

In [117]:
np.random.randint(19,55,10)

array([36, 43, 34, 31, 38, 30, 41, 31, 34, 40])

In [118]:
sample_array=np.arange(12)

In [119]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [120]:
rand_array=np.random.randint(0,5,12)

In [121]:
rand_array

array([4, 2, 1, 0, 3, 4, 2, 4, 2, 4, 3, 0])

In [152]:
sample_array=np.arange(12)
sample_array.reshape(5,6)

ValueError: cannot reshape array of size 12 into shape (5,6)

In [153]:
sample_array=np.arange(12)
sample_array.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
sample_array.reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [125]:
rand_array.max()

4

In [126]:
rand_array.argmax()

0

In [127]:
a=np.eye(5)

In [128]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [129]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [130]:
sample_array=np.arange(10,20)

In [131]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [132]:
sample_array[0]

10

In [133]:
sample_array[4]

14

In [137]:
sample_array[3:5]

array([3, 4])

In [139]:
sample_array[1:4]=100
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [140]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [141]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [142]:
subset_sample_array=sample_array[0:7]

In [143]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

### two dimensional techniques

In [144]:
sample_matrix=np.array([[50,10,1,23],[67,34,56,2],[2,3,4,5]])
sample_matrix

array([[50, 10,  1, 23],
       [67, 34, 56,  2],
       [ 2,  3,  4,  5]])

In [145]:
sample_matrix[1,2]

56

In [146]:
sample_matrix[2,:]

array([2, 3, 4, 5])

In [147]:
sample_matrix[2]

array([2, 3, 4, 5])

In [149]:
sample_matrix[:,(2,3)]

array([[ 1, 23],
       [56,  2],
       [ 4,  5]])

### Selection techniques

In [159]:
sample_array=np.arange(1,12)

In [160]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [161]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [162]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [163]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479])

In [164]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [165]:
np.max(sample_array)

11

In [166]:
np.min(sample_array)

1

In [167]:
np.argmax(sample_array)

10

In [168]:
np.argmin(sample_array)

0

In [169]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527])

In [170]:
np.std(sample_array)

3.1622776601683795

In [171]:
np.mean(sample_array)

6.0

In [172]:
np.median(sample_array)

6.0

In [173]:
np.mode(sample_array)

AttributeError: module 'numpy' has no attribute 'mode'

In [174]:
np.var(sample_array)

10.0

In [176]:
array=np.random.randn(3,4)

In [177]:
array

array([[ 1.0332735 ,  1.67345577, -1.11391331, -0.65201706],
       [-0.28395964, -0.17191872,  1.1906759 ,  0.64284866],
       [-3.05563823, -0.20828254, -0.22601632, -1.35234286]])

In [178]:
np.round(array,decimals=2)

array([[ 1.03,  1.67, -1.11, -0.65],
       [-0.28, -0.17,  1.19,  0.64],
       [-3.06, -0.21, -0.23, -1.35]])

In [179]:
sports=np.array(['cricket','golf','kabaddi','fball'])
np.unique(sports)

array(['cricket', 'fball', 'golf', 'kabaddi'], dtype='<U7')

### Pandas dataframe and indexing

In [181]:
import pandas as pd
import numpy as np

In [182]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','golf','base ball'])
sports1

cricket      1
football     2
golf         3
base ball    4
dtype: int64

In [184]:
sports1['football']

2

In [185]:
sports2=pd.Series(['cricket','football','basket ball','golf'])
sports2

0        cricket
1       football
2    basket ball
3           golf
dtype: object

In [186]:
sports1+sports2

0            NaN
1            NaN
2            NaN
3            NaN
base ball    NaN
cricket      NaN
football     NaN
golf         NaN
dtype: object

In [187]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.021069  0.659242  0.853299  0.085133  0.586590
B  0.946385  0.773186  0.432968  0.525364  0.799459
C  0.567918  0.797577  0.441864  0.438538  0.896665
D  0.962241  0.591290  0.923417  0.373523  0.402442
E  0.536425  0.751285  0.295223  0.345890  0.603466
F  0.425198  0.317768  0.907894  0.487595  0.481902
G  0.135870  0.724376  0.562034  0.021492  0.939096
H  0.561310  0.769456  0.221470  0.499435  0.956188

In [188]:
df1["score1"]

A    0.021069
B    0.946385
C    0.567918
D    0.962241
E    0.536425
F    0.425198
G    0.135870
H    0.561310
Name: score1, dtype: float64

In [191]:
df1[["score1","score2","score3"]]


score1    score2    score3
A  0.021069  0.659242  0.853299
B  0.946385  0.773186  0.432968
C  0.567918  0.797577  0.441864
D  0.962241  0.591290  0.923417
E  0.536425  0.751285  0.295223
F  0.425198  0.317768  0.907894
G  0.135870  0.724376  0.562034
H  0.561310  0.769456  0.221470

In [194]:
df1['score6']=df1['score1']+df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.021069  0.659242  0.853299  0.085133  0.586590  0.680311
B  0.946385  0.773186  0.432968  0.525364  0.799459  1.719570
C  0.567918  0.797577  0.441864  0.438538  0.896665  1.365496
D  0.962241  0.591290  0.923417  0.373523  0.402442  1.553531
E  0.536425  0.751285  0.295223  0.345890  0.603466  1.287710
F  0.425198  0.317768  0.907894  0.487595  0.481902  0.742966
G  0.135870  0.724376  0.562034  0.021492  0.939096  0.860246
H  0.561310  0.769456  0.221470  0.499435  0.956188  1.330766

In [228]:
df2={'ID':['101','102','103','104','105'],'name':['john','sindhu','vaishu','anusha','binny'],'profit':[23,45,67,43,34]}
df=pd.DataFrame(df2)
df

ID    name  profit
0  101    john      23
1  102  sindhu      45
2  103  vaishu      67
3  104  anusha      43
4  105   binny      34

In [229]:
df["ID"]

0    101
1    102
2    103
3    104
4    105
Name: ID, dtype: object

In [230]:
df[["ID","name"]]

ID    name
0  101    john
1  102  sindhu
2  103  vaishu
3  104  anusha
4  105   binny

In [231]:
df=df.drop("ID",axis=1)


In [232]:
df

name  profit
0    john      23
1  sindhu      45
2  vaishu      67
3  anusha      43
4   binny      34

In [233]:
df.drop(3)

name  profit
0    john      23
1  sindhu      45
2  vaishu      67
4   binny      34